apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: reddy-nginx-ingress
  namespace: dev

spec:
  ingressClassName: nginx

  rules:
  - host: dev.sg.app

    http:
      paths:
      - path: /
        pathType: Prefix

        backend:
          service:
            name: reddy-nginx-service
            port:
              number: 80