apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddy-nginx
  namespace: prod

spec:
  replicas: 3

  selector:
    matchLabels:
      app: reddy-nginx

  template:
    metadata:
      labels:
        app: reddy-nginx

    spec:
      containers:
      - name: reddy-nginx
        image: reddy-nginx-prod:v1
        ports:
        - containerPort: 80