apiVersion: apps/v1
kind: Deployment

metadata:
  name: reddy-nginx

spec:
  replicas: 2

  selector:
    matchLabels:
      app: reddy-nginx

  template:
    metadata:
      labels:
        app: reddy-nginx

    spec:
      containers:
      - name: reddy-nginx
        image: reddy-nginx:v1

        ports:
        - containerPort: 80